"""Generate printable patrol briefing cards for field officers."""
from datetime import datetime
from typing import Optional


def format_route_sequence(stops: list[dict]) -> str:
    if not stops:
        return "No stops assigned"
    return " → ".join(s["junction"] for s in stops)


def _unit_field_card(
    route: dict,
    shift_label: str,
    shift_hours: float,
    arrival_windows: Optional[list[str]] = None,
) -> list[str]:
    """One printable card per patrol unit."""
    now = datetime.now().strftime("%d %b %Y")
    lines = [
        "┌─────────────────────────────────────────────┐",
        f"│  FIELD CARD — UNIT {route['unit']}                          │",
        f"│  Officer: _______________________           │",
        f"│  Shift: {shift_label} ({shift_hours:.0f}h)                    │"[:47] + "│",
        "├─────────────────────────────────────────────┤",
        f"│  PCIS target: {route['route_pcis']:,.0f}  |  Stops: {route['n_stops']}          │"[:47] + "│",
        "│  STOP SEQUENCE:                             │",
    ]
    windows = arrival_windows or []
    for i, stop in enumerate(route["stops"], 1):
        jshort = stop["junction"].split(" - ", 1)[-1][:28]
        win = windows[i - 1] if i - 1 < len(windows) else "—"
        lines.append(f"│  {i}. [{win}] {jshort}"[:47] + "│")
    lines.extend([
        "├─────────────────────────────────────────────┤",
        f"│  Generated by PRAHARI · {now} · BTP field   │"[:47] + "│",
        "│  deployment                                 │",
        "└─────────────────────────────────────────────┘",
        "",
    ])
    return lines


def generate_briefing_text(
    routes: list[dict],
    shift_hours: float,
    total_pcis: float,
    comparison: Optional[dict] = None,
    shift_label: str = "Morning",
    arrival_windows_by_unit: Optional[dict] = None,
) -> str:
    """Plain-text field cards — one per officer."""
    now = datetime.now().strftime("%d %b %Y, %H:%M IST")
    est_stops = sum(len(r["stops"]) for r in routes)
    est_fines = est_stops * 500

    lines = [
        "═══════════════════════════════════════════",
        "  PRAHARI — FIELD DEPLOYMENT CARDS",
        "  Bengaluru Traffic Police | ASTraM",
        "═══════════════════════════════════════════",
        f"Generated: {now}",
        f"Shift: {shift_label} ({shift_hours:.0f} hours)",
        f"Units: {len(routes)} | PCIS target: {total_pcis:,.0f} | Stops: {est_stops}",
        "",
    ]

    for route in routes:
        wins = (arrival_windows_by_unit or {}).get(route["unit"], [])
        lines.extend(_unit_field_card(route, shift_label, shift_hours, wins))

    lines.extend([
        "COMMAND NOTES",
        "  • Dwell ~30 min per stop; prioritize heavy-vehicle violations",
        "  • PCIS = Parking Congestion Impact Score",
        "═══════════════════════════════════════════",
    ])
    return "\n".join(lines)


def generate_briefing_html(
    routes: list[dict],
    shift_hours: float,
    total_pcis: float,
    shift_label: str = "Morning",
    arrival_windows_by_unit: Optional[dict] = None,
) -> str:
    """HTML field cards for browser print — one page-break per unit."""
    now = datetime.now().strftime("%d %b %Y, %H:%M IST")
    est_stops = sum(len(r["stops"]) for r in routes)

    unit_blocks = []
    for route in routes:
        wins = (arrival_windows_by_unit or {}).get(route["unit"], [])
        stops_html = ""
        for i, s in enumerate(route["stops"], 1):
            win = wins[i - 1] if i - 1 < len(wins) else "—"
            stops_html += f"<li><span class='time'>[{win}]</span> <strong>{s['junction']}</strong> — PCIS {s['pcis']:,.0f}</li>"
        unit_blocks.append(f"""
        <div class="field-card">
          <div class="card-header">FIELD CARD — UNIT {route['unit']}</div>
          <p class="officer-line">Officer: _______________________</p>
          <p class="meta">{shift_label} shift · {shift_hours:.0f}h · PCIS {route['route_pcis']:,.0f}</p>
          <ol>{stops_html}</ol>
          <p class="footer">Generated by PRAHARI · {now} · for BTP field deployment</p>
        </div>
        """)

    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>PRAHARI Field Cards</title>
<style>
  body {{ font-family: Arial, sans-serif; max-width: 700px; margin: 16px auto; color: #111; }}
  .field-card {{
    border: 2px solid #1a73e8; border-radius: 8px; padding: 16px 20px;
    margin-bottom: 24px; page-break-after: always;
  }}
  .card-header {{ font-size: 1.2em; font-weight: bold; color: #1a73e8; margin-bottom: 8px; }}
  .officer-line {{ border-bottom: 1px solid #ccc; padding-bottom: 4px; }}
  .meta {{ color: #555; font-size: 0.9em; }}
  .time {{ color: #1a73e8; font-weight: bold; }}
  .footer {{ font-size: 0.8em; color: #888; margin-top: 12px; border-top: 1px solid #eee; padding-top: 8px; }}
  @media print {{ .field-card {{ page-break-after: always; }} }}
</style></head><body>
<h1>PRAHARI Field Cards — {len(routes)} Officers</h1>
<p>{shift_label} · {est_stops} stops · PCIS {total_pcis:,.0f}</p>
{''.join(unit_blocks)}
</body></html>"""
